### ISSUE TITLE
Add a flag to force unlocking the database tables at startup

### ISSUE THREAD

**Issue by krasi-georgiev** [traccar/traccar-docker#81]
We are running traccar on a Rpi which runs on battery and quite often it doesn't get shutdown gracefully which leaves the db tables lockes.
Would you accept a PR that adds a flag at startup that forces db unlocking?

something like
```
java -cp lib/h2*.jar org.h2.tools.Shell -url "jdbc:h2:/opt/traccar/data/database" -driver org.h2.Driver -user sa
SELECT * FROM PUBLIC.DATABASECHANGELOGLOCK;
update PUBLIC.DATABASECHANGELOGLOCK set locked=0 WHERE ID=1;
```

**Comment by meilon** [comment]
I'm against hard coding this into the container because I don't use H2, instead I use MariaDB.
Instead I'd welcome moving to an entrypoint.sh which actually starts traccar (and not using CMD). This script could check if a file exists at a predefined location and execute it. This way pre-start would be customizable without rebuilding the image.

Maybe migrating over to s6-overlay or how linuxserver.io does it makes using this container more like the others without special implementations

**Comment by krasi-georgiev** [comment]
yes an entrypoint file would work.

**Comment by krasi-georgiev** [comment]
any comment from the maintainers?

**Comment by krasi-georgiev** [comment]
ping

**Comment by krasi-georgiev** [comment]
ping

**Comment by tananaev** [comment]
I agree that it doesn't make sense to hardcode something like this.

**Comment by krasi-georgiev** [comment]
@tananaev the question is for this change

> Instead I'd welcome moving to an entrypoint.sh which actually starts traccar (and not using CMD). This script could check if a file exists at a predefined location and execute it. This way pre-start would be customizable without rebuilding the image.

**Comment by tananaev** [comment]
I personally like the clean solution we have now. I feel like it's in a true spirit of Docker.

I'm also not sure if locked database is a real issue. Database is temporarily locked only on launch, so even if you lose battery and shutdown the server after the launch, it shouldn't happen.

**Comment by krasi-georgiev** [comment]
yes I think you are right it did happen during initialization. so lets leave as is and will spend more time on this when/if needed
